-- Active: 1769825708786@@mysql-3dd86230-codis1723-5bb1.h.aivencloud.com@13920
-- Active: 1769825093434@@mysql-3dd86230-codis1723-5bb1.h.aivencloud.com@13920
CREATE DATABASE IF NOT EXISTS leaner_beam_db;
USE leaner_beam_db;

CREATE TABLE USER_BASE(
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    FAILED_ATTEMPTS INT DEFAULT 0,
    LAST_LOGIN DATETIME,
    LAST_FAILED_LOGIN DATETIME,
    LOCKED BOOLEAN DEFAULT FALSE,
    LOCK_REASON VARCHAR(255),
    ACTIVE BOOLEAN DEFAULT TRUE,
    reset_code_hash VARCHAR(255),
    reset_code_expires DATETIME,

  
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CUST_BASE (
    CUST_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    country VARCHAR(100),
    currency VARCHAR(10),   
    FOREIGN KEY (USER_ID) REFERENCES USER_BASE(USER_ID) ON DELETE CASCADE   
);

CREATE TABLE IF NOT EXISTS WALLET_BASE (
    WALLET_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    balance DECIMAL(15, 2) DEFAULT 0.00,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER_BASE(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRANSACTION_BASE (
    TRANSACTION_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    amount DECIMAL(15, 2) NOT NULL,
    transaction_type ENUM('WITHDRAW', 'TRADE PROFIT', 'DEPOSIT') NOT NULL,
    status ENUM('PENDING', 'COMPLETED', 'FAILED') DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER_BASE(USER_ID) ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS ADMIN_BASE (
    admin_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('admin', 'superadmin') DEFAULT 'admin',
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

drop table ADMIN_BASE;
ALTER TABLE CUST_BASE ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE USER_BASE ADD COLUMN email_verified BOOLEAN DEFAULT FALSE AFTER ACTIVE;

DROP TABLE IF EXISTS CUST_BASE;

DROP TABLE IF EXISTS WALLET_BASE;

DROP TABLE IF EXISTS TRANSACTION_BASE;
DROP TABLE IF EXISTS USER_BASE;

SELECT * FROM USER_BASE;

SELECT * FROM ADMIN_BASE;

ALTER TABLE TRANSACTION_BASE ADD COLUMN description VARCHAR(255) AFTER amount;

ALTER TABLE ADMIN_BASE DROP COLUMN USER_ID;